export const Styles = {
  container: {
    display: "flex",
    minHeight: "80vh",
    fontFamily: "Inter, Arial, sans-serif",
    background: "#f9fafb",
  },
  sidebar: {
    width: "320px",
    background: "#f3f4f6",
    borderRight: "1px solid #e5e7eb",
    padding: "24px 0 24px 0",
    overflowY: "auto",
  },
  moduleTitle: {
    fontWeight: "bold",
    fontSize: "1.1rem",
    padding: "12px 20px",
    cursor: "pointer",
    borderBottom: "1px solid #e5e7eb",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  progressBarWrap: {
    position: "relative",
    height: "8px",
    background: "#e5e7eb",
    borderRadius: "4px",
    marginTop: "6px",
    marginBottom: "2px",
    width: "100%",
  },
  progressBar: {
    position: "absolute",
    left: 0,
    top: 0,
    height: "8px",
    background: "#6366f1",
    borderRadius: "4px",
    transition: "width 0.3s",
  },
  progressText: {
    fontSize: "0.8rem",
    color: "#6366f1",
    marginTop: "10px",
    fontWeight: "bold",
  },
  lessonList: {
    listStyle: "none",
    margin: 0,
    padding: "0 0 0 10px",
  },
  lessonItem: {
    padding: "10px 18px",
    cursor: "pointer",
    borderBottom: "1px solid #e5e7eb",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "1rem",
    transition: "background 0.2s",
  },
  checkmark: {
    fontSize: "1.2rem",
    color: "#10b981",
    width: "24px",
    textAlign: "center",
  },
  main: {
    flex: 1,
    padding: "32px 40px",
    background: "#fff",
    minHeight: "80vh",
  },
  lessonStatusWrap: {
    display: "flex",
    alignItems: "center",
    gap: "24px",
    marginBottom: "18px",
  },
  completeBtn: {
    padding: "8px 18px",
    background: "#6366f1",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    fontWeight: "bold",
    cursor: "pointer",
    fontSize: "1rem",
    transition: "background 0.2s",
    opacity: 1,
  },
  moduleProgressBarWrap: {
    position: "relative",
    width: "180px",
    height: "8px",
    background: "#e5e7eb",
    borderRadius: "4px",
    marginRight: "8px",
  },
  moduleProgressBar: {
    position: "absolute",
    left: 0,
    top: 0,
    height: "8px",
    background: "#6366f1",
    borderRadius: "4px",
    transition: "width 0.3s",
  },
  moduleProgressText: {
    fontSize: "0.9rem",
    color: "#6366f1",
    marginLeft: "12px",
    fontWeight: "bold",
  },
  uploadSection: {
    margin: "32px 0 24px 0",
    padding: "18px 24px",
    background: "#f3f4f6",
    borderRadius: "8px",
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
  },
  fileInput: {
    margin: "12px 0",
    padding: "6px",
    fontSize: "1rem",
  },
  uploadList: {
    listStyle: "none",
    margin: "10px 0 0 0",
    padding: 0,
  },
  uploadItem: {
    fontSize: "0.98rem",
    marginBottom: "4px",
    color: "#374151",
  },
  uploadDate: {
    fontSize: "0.85rem",
    color: "#6b7280",
    marginLeft: "8px",
  },
  lessonContent: {
    marginTop: "32px",
    fontSize: "1.08rem",
    color: "#374151",
    background: "#f9fafb",
    padding: "18px 24px",
    borderRadius: "8px",
  },
};
